<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Access\AccessResult;

/**
 * Implements hook_theme().
 */
function custom_module_1_theme($existing, $type, $theme, $path) {
  return [
    'my_template' => [
      'variables' => ['ad' => NULL, 'soyad' => NULL],
    ],
  ];
}

// function custom_module_1_entity_access(EntityInterface $entity, $operation, \Drupal\Core\Session\AccountInterface $account) {
//   $entityid = $entity->getEntityType()->id();
//   if ($entityid == "node" && $entity->bundle() == "component") {
//     // $visible = $entity->field_basic_page_anonymous->value;
//     $userID = \Drupal::currentUser()->id();
//     $currentUser = \Drupal::entityTypeManager()->getStorage('user')->load($userID);
//     if ($currentUser->status->value != 1) {
//       return AccessResult::forbidden();
//     }
//     // if ($visible != 1 && \Drupal::currentUser()->isAnonymous() == true) {
//     //   return AccessResult::forbidden();
//     // }
//     return AccessResult::neutral();
//   }
// }

function custom_module_1_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == "node_page_form") {
    $currentUser = \Drupal::currentUser();
    if ($currentUser->hasPermission('add content formu erisimi') == FALSE) {
      $form['field_basic_page_anonymous']['#access'] = FALSE;
    }
    // $roles = $currentUser->getRoles();
    // if (in_array('content_editor', $roles)) {
    //   $form['field_basic_page_anonymous']['#access'] = FALSE;
    // }
  }
}

function custom_module_1_cron() {
  \Drupal::logger('my_module')->error('çalıştı');
}